//* module.exports = {
  //tutorialSidebar: {
    //'Getting started': ['intro to Axonect'],
  //},
// };
module.exports = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};